### ISSUE TITLE
能搞个只是定位功能的模块吗

### ISSUE THREAD

**Issue by 0x55aa** [yiyangest/react-native-yyamap#2]
造福一下我们这些不会写原生的人 哈哈

**Comment by yiyangest** [comment]
不要地图，只要定位的经纬度吗

**Comment by 0x55aa** [comment]
http://lbs.amap.com/getting-started/locate/
有时间搞吗 哈哈。只能找到安卓版的 多谢啊

**Comment by 0x55aa** [comment]
有时间搞吗，不行我就硬着头皮上了

**Comment by yiyangest** [comment]
前段时间太忙了。。周末搞吧。

**Comment by 0x55aa** [comment]
多谢啊，太给力了

**Comment by yiyangest** [comment]
see [react-native-amaplocating](https://github.com/yiyangest/react-native-amaplocating).

**Comment by 0x55aa** [comment]
多谢，解决了我一大问题啊
