### ISSUE TITLE
[ios]设置了region，不会定位到对应中心点

### ISSUE THREAD

**Issue by ljspace** [yiyangest/react-native-yyamap#4]
您好，在iOS下设置了region属性，不会定位到对应中心点，不知道是什么原因。

能否在设置中心点的时候考虑增加 zoom 值的设置，谢谢。

iOS 版本RN组件部署说明里面没提到配置apiKey，是不需要配置 apiKey 吗？

iOS  9.3.2
react  15.1.0
react-native 0.27.0-rc2 

``` js
<MapView
    style={{flex:1, width: 300}}                                
    region={{
        latitude: 26.069042, 
        longitude: 119.310118,
        latitudeDelta: 1,
        longitudeDelta: 1,
    }}                                
    annotations={this.state.annotations}
/>   
```

**Comment by yiyangest** [comment]
需要配置APIKey，在iOS的Appdelegate里进行配置

```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{

  BMKMapManager *mapManager = [[BMKMapManager alloc] init];
  BOOL ret = [mapManager start:@"xxxx--api key--xxxx" generalDelegate:nil];
  if (!ret) {
    NSLog(@"map manager start failed");
  }
  ...
}
```

**Comment by ljspace** [comment]
@yiyangest  非常感谢你的回复。

上面代码提供的应该是百度地图SDK的apiKey设置，`react-native-yyamap`组件用的是高德地图SDK，你可能弄混了。

后面我看了高德官网的说明加了apiKey的设置，但是`setRegion`方法还是没效果。

```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  NSURL *jsCodeLocation;

  [MAMapServices sharedServices].apiKey = @"xxxx--api key--xxxx";

 ……
}
```

本人没做过 oc 开发，所以不是很懂，只能大致 Xcode 断点跟踪了下代码，发现有调用到 oc 里面的 `setRegion` 方法，参数也都正确，但是就是地图没定位到我传人的区域，很是疑惑。

设置 region 后触发的 `_regionChanged` 回调里面断点看了下 `mapView.region` 还是初始化时的 region 数据。

调试截图
<img src="http://i4.piimg.com/4851/247829b113b73a0e.png">

**Comment by ljspace** [comment]
找到原因了，我地图没有默认显示，是在另外一个页面弹出显示，所以会导致地图组件还没显示出来，代码就已经执行了，加了个延迟调用 `setRegion` 就正常了。
